version: "3.7"

services:
  db:
    image: mysql:8
    volumes:
      - ./db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=1G --tmp_table_size=1G --max_heap_table_size=1G
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE

  book-lab-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./:/app/
